// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtHsxyVAktk4Nes7zWpuDPygzNPkXq0NU',
    appId: '1:326241835689:web:8221d506315ccf414a27b8',
    messagingSenderId: '326241835689',
    projectId: 'todo-bloc-firebase',
    authDomain: 'todo-bloc-firebase.firebaseapp.com',
    storageBucket: 'todo-bloc-firebase.appspot.com',
    measurementId: 'G-0DFLC3NJJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaUVY_DnmAMhDBYbELGJipXMJDE-oXAuA',
    appId: '1:326241835689:android:da991251bc2ce53d4a27b8',
    messagingSenderId: '326241835689',
    projectId: 'todo-bloc-firebase',
    storageBucket: 'todo-bloc-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIlEUEI0hF7oK8LxFo96lD7nDMXYLDCaE',
    appId: '1:326241835689:ios:6937817822dac0784a27b8',
    messagingSenderId: '326241835689',
    projectId: 'todo-bloc-firebase',
    storageBucket: 'todo-bloc-firebase.appspot.com',
    iosBundleId: 'com.example.todoBlocFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIlEUEI0hF7oK8LxFo96lD7nDMXYLDCaE',
    appId: '1:326241835689:ios:64955e639e1d026f4a27b8',
    messagingSenderId: '326241835689',
    projectId: 'todo-bloc-firebase',
    storageBucket: 'todo-bloc-firebase.appspot.com',
    iosBundleId: 'com.example.todoBlocFirestore.RunnerTests',
  );
}
